











print(isinstance(12,(str,int))) # перемменая типы int

# for val in [1, 2, 3, 4, 5, [6, 7, 8, 5, 6], (4, 5, 6)]: 
#     print(val) 
#     if isinstance(val, (list, set, tuple)):  # true
#         for i in val: 
#             print(i)

# for val in [1, 2, 3, 4, 5, [6, 7, 8, 5, 6], (4, 5, 6)]: 
#     if isinstance(val, (list, set, tuple)): 
#         for i in val: 
#             print(i)
#     else:
#         print(val)


# a = [1,2, "hello",4,5,6,7]
# #[4,8,12,16,20,24]
# b = []
# print(b)
# for val in a:
#     if isinstance(val,(int,float)):
#         b.append(val * 4) # 1 * 4 = 4

# print(b)        

# a, b, *args =(2,4,4,7,8,9,0)
# print(a,b, args)

# for i in range(10): # 4-9
#     print(i)

# print("Next range")  

# for i in range(4, 10): # 4-9
#     print(i)

# print("Next range")  
# for i in range(4, 10, 2): # 4-9
#     print(i)    
# info = []

# info = [
# {
#     "name" : "ifhajdos",
#     "age" : "12"
# },
#  {"name" : "ifhajdos",
#     "age" : "12"
# }
# ]


    
     

